branches:
  only:
  - master

language: minimal

addons:
  apt:
    packages:
    - gfortran
    - libnetcdff-dev

script:
- ./configure --prefix=$(pwd)/install 'NETCDF_FCFLAGS=-I/usr/include' 'NETCDF_FCLIBS=-L/usr/lib/x86_64-linux-gnu -lnetcdff' || { cat ./config.log; exit 1; }
- make -j4
- make -j4 install
- ./install/bin/main
- make -j4 distclean
- ./configure --disable-openmp --disable-silent-rules
- make -j4
- ./main

